"use client";
import React from "react";
import type { Resume } from "@/lib/resume-schema"; import { nextId } from "@/lib/resume-schema"; import { Plus, Trash2 } from "lucide-react";
import { AnimatedSection, SectionHeader, Field, CollapsibleItem, FormattedField, inputCls, btnCls } from "../shared";
import { useLocale } from "@/lib/locale-provider";
interface Props { resume: Resume; onChange: (r: Resume) => void; openSections: Record<string, boolean>; toggle: (k: string) => void; visible: (k: string) => boolean; togVis: (k: string) => void; sectionTitle: (k: string, f: string) => string; sectionIconEl: (k: string, f: string) => React.ReactNode; sLabel: (k: string, v: string) => void; sIcon: (k: string, f: string) => string; sIconSet: (k: string, v: string) => void; onMoveUp?: () => void; onMoveDown?: () => void; isFirst?: boolean; isLast?: boolean; }
export default function ProjectsSection({ resume, onChange, openSections, toggle, visible, togVis, sectionTitle, sectionIconEl, sLabel, sIcon, sIconSet, onMoveUp, onMoveDown, isFirst, isLast }: Props) {
  const { t } = useLocale();
  function moveItem(idx: number, dir: number) { const arr = [...resume.projects]; const target = idx + dir; if (target < 0 || target >= arr.length) return; const a = arr[idx]!, b = arr[target]!; arr[idx] = b; arr[target] = a; onChange({ ...resume, projects: arr }); }
  return (<><SectionHeader title={sectionTitle("projects", "PROJECTS")} count={resume.projects.length} icon={sectionIconEl("projects", "folder-git")} open={!!openSections.projects} onToggle={() => toggle("projects")} visible={visible("projects")} onToggleVisibility={() => togVis("projects")} sectionKey="projects" onTitleChange={sLabel} iconKey={sIcon("projects","folder-git")} onIconChange={k => sIconSet("projects",k)} onMoveUp={onMoveUp} onMoveDown={onMoveDown} isFirst={isFirst} isLast={isLast} /><AnimatedSection open={!!openSections.projects}><div className="px-2 pb-3 space-y-1">
    {resume.projects.map((proj, idx) => (<CollapsibleItem key={proj.id} title={proj.name || t("projects.newItem")} open={!!openSections[proj.id]} onToggle={() => toggle(proj.id)} onMoveUp={() => moveItem(idx, -1)} onMoveDown={() => moveItem(idx, 1)} isFirst={idx === 0} isLast={idx === resume.projects.length - 1} onDelete={() => onChange({ ...resume, projects: resume.projects.filter(x => x.id !== proj.id) })}>
      <Field label="Name"><input className={inputCls} value={proj.name} onChange={e => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, name: e.target.value } : x) })} /></Field>
      <div className="flex gap-2"><div className="flex-1"><Field label={t("projects.role")}><input className={inputCls} value={proj.role} onChange={e => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, role: e.target.value } : x) })} /></Field></div><div className="flex-1"><Field label={t("projects.affiliation")}><input className={inputCls} value={proj.affiliation} onChange={e => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, affiliation: e.target.value } : x) })} /></Field></div></div>
      <div className="flex gap-2"><div className="flex-1"><Field label="Start Date"><input className={inputCls} value={proj.startDate} onChange={e => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, startDate: e.target.value } : x) })} /></Field></div><div className="flex-1"><Field label="End Date"><input className={inputCls} value={proj.endDate} onChange={e => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, endDate: e.target.value } : x) })} /></Field></div></div>
      <Field label="URL"><input className={inputCls} value={proj.url} onChange={e => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, url: e.target.value } : x) })} /></Field>
      <FormattedField label={t("projects.description")} value={proj.description} onChange={v => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, description: v } : x) })} />
      <div><span className="text-[10px] text-slate-400 uppercase tracking-wider block mb-2">Technologies</span>
        {proj.technologies.map((t, i) => (<div key={i} className="flex gap-1.5 items-center mb-2"><input className={inputCls} value={t} onChange={e => { const tech = [...proj.technologies]; tech[i] = e.target.value; onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, technologies: tech } : x) }); }} /><button onClick={() => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, technologies: proj.technologies.filter((_, j) => j !== i) } : x) })} className="p-1 text-slate-300 hover:text-red-400"><Trash2 className="w-4 h-4" /></button></div>))}
        <button onClick={() => onChange({ ...resume, projects: resume.projects.map(x => x.id === proj.id ? { ...x, technologies: [...x.technologies, ""] } : x) })} className={btnCls}><Plus className="w-3 h-3" />{t("projects.addTech")}</button>
      </div>
    </CollapsibleItem>))}
    <button onClick={() => onChange({ ...resume, projects: [...resume.projects, { id: nextId(), name: "", role: "", affiliation: "", startDate: "", endDate: "", description: "", url: "", technologies: [] }] })} className={btnCls}><Plus className="w-3 h-3" />{t("projects.add")}</button>
  </div></AnimatedSection></>);
}
